### ISSUE TITLE
CI setup

### ISSUE THREAD

**Issue by theodorsm** [ItemizeNTNU/website#8]
Add a GH action for liting and some testing.

**Comment by kristianvld** [comment]
Maybe add ajinabraham/NodeJsScan?

**Comment by kristianvld** [comment]
## Tasks:

- [x] Eslint - cli
- [x] Eslint - Github Action
- [x] Prettier - cli
- [x] Prettier - Github Action
- [x] DepCheck - cli
- [x] DepCheck - Github Action
- [ ] NodeJsScan - cli
- [ ] NodeJsScan - Github Action

Other code analysis tools we should add?
